server:
  port: 8000
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
ratelimiting:
  max-requests: 100
  window-size: 60000
