server:
  port: 8000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
